import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled, { ThemeProvider } from "styled-components";
import { theme } from "../styles/theme/theme";
import { Introduction } from "../views/introduction/introduction";

const Container = styled.div`
  padding: 0 2rem;
`;
export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <Container>
        <Head>
          <title>Cody Spate</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon-16x16.png"
          />
          <link rel="manifest" href="/site.webmanifest" />
        </Head>
        <Introduction />
      </Container>
    </ThemeProvider>
  );
}
